import Footer from "./components/Footer/Footer";
import Navbar from "./components/Navbar/Navbar";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Distant Learning - EduBlink Online",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
